export interface MapTemplate {
  id: number;
  name: string;
  status: "ONLINE" | "OFFLINE";
  planet: string;
}

export const MAP_TEMPLATES: MapTemplate[] = [
  { id: 0, name: "Núi Paozu", status: "ONLINE", planet: "EARTH" },
  { id: 1, name: "Bờ sông Pu", status: "ONLINE", planet: "EARTH" },
  { id: 2, name: "Thác nước Keise", status: "ONLINE", planet: "EARTH" },
  { id: 115, name: "Võ đài Cell", status: "ONLINE", planet: "EARTH" },
  { id: 3, name: "Rừng nấm Fuka", status: "ONLINE", planet: "EARTH" },
  { id: 4, name: "Đồi hoang Aka", status: "ONLINE", planet: "EARTH" },
  { id: 5, name: "Thung lũng Maria", status: "ONLINE", planet: "EARTH" },
  { id: 6, name: "Đồng bằng Mika", status: "ONLINE", planet: "EARTH" },
  { id: 114, name: "Đấu trường", status: "OFFLINE", planet: "EARTH" },
  { id: 7, name: "Cao nguyên Taka", status: "ONLINE", planet: "EARTH" },
  { id: 8, name: "Rừng Goza", status: "ONLINE", planet: "EARTH" },
  { id: 9, name: "Vách núi Paozu", status: "ONLINE", planet: "EARTH" },
  { id: 10, name: "Làng Aru", status: "ONLINE", planet: "EARTH" },
  { id: 11, name: "Thành phố Pein", status: "ONLINE", planet: "EARTH" },
  { id: 12, name: "Trạm tàu vũ trụ", status: "ONLINE", planet: "EARTH" },
  { id: 13, name: "Thành phố nấm", status: "ONLINE", planet: "EARTH" },
  { id: 14, name: "Thành phố phía nam", status: "ONLINE", planet: "EARTH" },
  { id: 15, name: "Bờ vực Giran", status: "ONLINE", planet: "EARTH" },
  { id: 16, name: "Vực Giran", status: "ONLINE", planet: "EARTH" },
  { id: 17, name: "Rừng Giran", status: "ONLINE", planet: "EARTH" },
  { id: 18, name: "Rừng nguyên thủy", status: "ONLINE", planet: "EARTH" },
  { id: 19, name: "Đảo Kamê", status: "ONLINE", planet: "EARTH" },
  { id: 20, name: "Thánh địa Karin", status: "ONLINE", planet: "EARTH" },
  { id: 21, name: "Tháp Karin", status: "ONLINE", planet: "EARTH" },
  { id: 22, name: "Đại hội võ thuật", status: "ONLINE", planet: "EARTH" },
  { id: 23, name: "Hoang mạc Sara", status: "ONLINE", planet: "EARTH" },
  { id: 24, name: "Phía đông Sara", status: "ONLINE", planet: "EARTH" },
  { id: 25, name: "Thành phố phía bắc", status: "ONLINE", planet: "EARTH" },
  { id: 26, name: "Phía bắc Sara", status: "ONLINE", planet: "EARTH" },
  { id: 27, name: "Phía tây Sara", status: "ONLINE", planet: "EARTH" },
  { id: 28, name: "Cổng Bản doanh", status: "OFFLINE", planet: "EARTH" },
  { id: 29, name: "Sân trước", status: "OFFLINE", planet: "EARTH" },
  { id: 30, name: "Sân sau", status: "OFFLINE", planet: "EARTH" },
  { id: 31, name: "Tháp canh", status: "OFFLINE", planet: "EARTH" },
  { id: 32, name: "Sân tập", status: "OFFLINE", planet: "EARTH" },
  { id: 33, name: "Phòng điều khiển", status: "OFFLINE", planet: "EARTH" },
  { id: 34, name: "Nhà kho", status: "OFFLINE", planet: "EARTH" },
  { id: 35, name: "Tường thành 1", status: "OFFLINE", planet: "EARTH" },
  { id: 36, name: "Tường thành 2", status: "OFFLINE", planet: "EARTH" },
  { id: 37, name: "Phòng giam", status: "OFFLINE", planet: "EARTH" },
  { id: 38, name: "Phòng chờ 1", status: "OFFLINE", planet: "EARTH" },
  { id: 39, name: "Phòng chờ 2", status: "OFFLINE", planet: "EARTH" },
  { id: 40, name: "Phòng chờ 3", status: "OFFLINE", planet: "EARTH" },
  { id: 41, name: "Tầng 1", status: "OFFLINE", planet: "EARTH" },
  { id: 42, name: "Tầng lầu", status: "OFFLINE", planet: "EARTH" },
  { id: 43, name: "Cửa không gian", status: "OFFLINE", planet: "SURVIVAL" },
  { id: 44, name: "Cửa 1", status: "OFFLINE", planet: "SURVIVAL" },
  { id: 45, name: "Cửa 2", status: "OFFLINE", planet: "SURVIVAL" },
  { id: 46, name: "Cửa 3", status: "OFFLINE", planet: "SURVIVAL" },
  { id: 47, name: "Lãnh địa", status: "OFFLINE", planet: "EARTH" },
  { id: 48, name: "Thành phố lãng quên", status: "OFFLINE", planet: "EARTH" },
  { id: 49, name: "Trạm tàu Namek", status: "ONLINE", planet: "NAMEK" },
  { id: 50, name: "Sườn núi Mori", status: "ONLINE", planet: "NAMEK" },
  { id: 51, name: "Núi Mori", status: "ONLINE", planet: "NAMEK" },
  { id: 52, name: "Đồi Mori", status: "ONLINE", planet: "NAMEK" },
  { id: 53, name: "Thung lũng Mori", status: "ONLINE", planet: "NAMEK" },
  { id: 54, name: "Làng Mori", status: "ONLINE", planet: "NAMEK" },
  { id: 55, name: "Vách núi Mori", status: "ONLINE", planet: "NAMEK" },
  { id: 56, name: "Làng Ốc sên", status: "ONLINE", planet: "NAMEK" },
  { id: 57, name: "Thị trấn hoang", status: "ONLINE", planet: "NAMEK" },
  { id: 58, name: "Làng Guru", status: "ONLINE", planet: "NAMEK" },
  { id: 59, name: "Thị trấn Guru", status: "ONLINE", planet: "NAMEK" },
  { id: 60, name: "Đảo Maima", status: "ONLINE", planet: "NAMEK" },
  { id: 61, name: "Rừng Guru", status: "ONLINE", planet: "NAMEK" },
  { id: 62, name: "Thung lũng Guru", status: "ONLINE", planet: "NAMEK" },
  { id: 63, name: "Làng Cổ Gira", status: "OFFLINE", planet: "NAMEK" },
  { id: 64, name: "Làng Monaito (1 sao)", status: "OFFLINE", planet: "NAMEK" },
  { id: 65, name: "Làng Dravo (2 sao)", status: "OFFLINE", planet: "NAMEK" },
  { id: 66, name: "Làng Tsuburi (3 sao)", status: "OFFLINE", planet: "NAMEK" },
  { id: 67, name: "Làng Shiro (4 sao)", status: "OFFLINE", planet: "NAMEK" },
  { id: 68, name: "Làng Kami (5 sao)", status: "OFFLINE", planet: "NAMEK" },
  { id: 69, name: "Làng Mori (6 sao)", status: "OFFLINE", planet: "NAMEK" },
  { id: 70, name: "Làng Tsuno (7 sao)", status: "OFFLINE", planet: "NAMEK" },
  { id: 71, name: "Thung lũng Siroi", status: "ONLINE", planet: "NAMEK" },
  { id: 72, name: "Thung lũng Turi", status: "ONLINE", planet: "NAMEK" },
  { id: 73, name: "Cửa lửa 1", status: "OFFLINE", planet: "FIRE" },
  { id: 74, name: "Cửa lửa 2", status: "OFFLINE", planet: "FIRE" },
  { id: 75, name: "Cửa lửa 3", status: "OFFLINE", planet: "FIRE" },
  { id: 76, name: "Cửa lửa 4", status: "OFFLINE", planet: "FIRE" },
  { id: 77, name: "Cửa lửa 5", status: "OFFLINE", planet: "FIRE" },
  { id: 78, name: "Cửa lửa 6", status: "OFFLINE", planet: "FIRE" },
  { id: 79, name: "Cửa băng 1", status: "OFFLINE", planet: "COLD" },
  { id: 80, name: "Cửa băng 2", status: "OFFLINE", planet: "COLD" },
  { id: 81, name: "Cửa băng 3", status: "OFFLINE", planet: "COLD" },
  { id: 82, name: "Cửa băng 4", status: "OFFLINE", planet: "COLD" },
  { id: 83, name: "Cửa băng 5", status: "OFFLINE", planet: "COLD" },
  { id: 84, name: "Cửa băng 6", status: "OFFLINE", planet: "COLD" },
  { id: 85, name: "Hang phía bắc", status: "OFFLINE", planet: "EARTH" },
  { id: 86, name: "Hang phía nam", status: "OFFLINE", planet: "EARTH" },
  { id: 87, name: "Hang trung tâm", status: "OFFLINE", planet: "EARTH" },
  { id: 88, name: "Thần điện", status: "ONLINE", planet: "EARTH" },
  { id: 94, name: "Băng hỏa 1", status: "OFFLINE", planet: "FIRE" },
  { id: 95, name: "Băng hỏa 3", status: "OFFLINE", planet: "FIRE" },
  { id: 96, name: "Băng hỏa 5", status: "OFFLINE", planet: "FIRE" },
  { id: 97, name: "Băng hỏa 7", status: "OFFLINE", planet: "FIRE" },
  { id: 98, name: "Băng hỏa 9", status: "OFFLINE", planet: "FIRE" },
  { id: 99, name: "Băng hỏa 11", status: "OFFLINE", planet: "FIRE" },
  { id: 100, name: "Băng hỏa 2", status: "OFFLINE", planet: "COLD" },
  { id: 101, name: "Băng hỏa 4", status: "OFFLINE", planet: "COLD" },
  { id: 102, name: "Băng hỏa 6", status: "OFFLINE", planet: "COLD" },
  { id: 103, name: "Băng hỏa 8", status: "OFFLINE", planet: "COLD" },
  { id: 104, name: "Băng hỏa 10", status: "OFFLINE", planet: "COLD" },
  { id: 105, name: "Băng hỏa 12", status: "OFFLINE", planet: "COLD" },
  { id: 89, name: "Rừng Amazon", status: "ONLINE", planet: "EARTH" },
  { id: 90, name: "Rừng Lily", status: "ONLINE", planet: "EARTH" },
  { id: 91, name: "Yardrat 1", status: "ONLINE", planet: "YARDRAT" },
  { id: 92, name: "Yardrat 2", status: "ONLINE", planet: "YARDRAT" },
  { id: 93, name: "Yardrat 3", status: "ONLINE", planet: "YARDRAT" },
  { id: 106, name: "Rừng chết 1", status: "ONLINE", planet: "EARTH" },
  { id: 107, name: "Rừng chết 2", status: "ONLINE", planet: "EARTH" },
  { id: 108, name: "Rừng chết 3", status: "ONLINE", planet: "EARTH" },
  { id: 109, name: "Rừng chết 4", status: "ONLINE", planet: "EARTH" },
  { id: 110, name: "Rừng chết 5", status: "ONLINE", planet: "EARTH" },
  { id: 111, name: "Rừng chết 6", status: "ONLINE", planet: "EARTH" },
  { id: 112, name: "Rừng chết 7", status: "ONLINE", planet: "EARTH" },
  { id: 113, name: "Rừng chết 8", status: "ONLINE", planet: "EARTH" },
  { id: 116, name: "Nhà Gohan", status: "OFFLINE", planet: "EARTH" },
  { id: 117, name: "Thánh địa", status: "OFFLINE", planet: "EARTH" },
  { id: 118, name: "Bưng Bư", status: "OFFLINE", planet: "EARTH" },
  { id: 119, name: "Đảo hoa 1", status: "OFFLINE", planet: "EARTH" },
  { id: 120, name: "Đảo hoa 2", status: "OFFLINE", planet: "EARTH" },
  { id: 121, name: "Phía bắc hành tinh Bill", status: "ONLINE", planet: "BILL" },
  { id: 122, name: "Phía tây hành tinh Bill", status: "ONLINE", planet: "BILL" },
  { id: 123, name: "Phía nam hành tinh Bill", status: "ONLINE", planet: "BILL" },
  { id: 124, name: "Phía đông hành tinh Bill", status: "ONLINE", planet: "BILL" },
  { id: 125, name: "Tầng 1", status: "OFFLINE", planet: "EARTH" },
  { id: 126, name: "Tầng 4", status: "OFFLINE", planet: "EARTH" },
  { id: 127, name: "Tầng 2", status: "OFFLINE", planet: "EARTH" },
  { id: 128, name: "Tầng 3", status: "OFFLINE", planet: "EARTH" },
  { id: 129, name: "Hành tinh ngục tù", status: "OFFLINE", planet: "EARTH" },
  { id: 130, name: "Băng hỏa 13", status: "OFFLINE", planet: "FIRE" },
  { id: 131, name: "Băng hỏa 14", status: "OFFLINE", planet: "COLD" },
  { id: 132, name: "Băng hỏa 15", status: "OFFLINE", planet: "FIRE" },
];
